"""German -> English names for the asset folder (see build_assets.py).

Original paths are lower-cased, split into words (on _ - space . digits and the like) and
each word is looked up here. Words the glossary does not know are kept as they are and
listed in the build report, so they can be added.
"""

# The four peoples, as the original folders and file names abbreviate them.
PEOPLE = {
    "usa": "americans", "mex": "mexicans", "ind": "natives", "indi": "natives", "indianer": "natives",
    "des": "outlaws", "desp": "outlaws", "desperados": "outlaws", "mexikaner": "mexicans",
}

WORDS = {
    # --- peoples and generic
    "usa": "americans", "mex": "mexicans", "ind": "natives", "indi": "natives", "indianer": "natives",
    "des": "outlaws", "desp": "outlaws", "desperados": "outlaws", "mexikaner": "mexicans",
    "mexican": "mexican", "american": "american", "native": "native",
    "einheit": "unit", "einheiten": "units", "gebäude": "buildings", "elemente": "nature",
    "icon": "icon", "icons": "icons", "sonstige": "other", "allgemein": "general",
    "neutrale": "neutral", "spieler": "player", "typ": "type", "type": "type",
    # --- units
    "infanterist": "infantryman", "infantrist": "infantryman", "kavallerist": "cavalryman",
    "kavelerist": "cavalryman", "kommandant": "commander", "befehlshaber": "commander",
    "landarbeiter": "farmhand", "arbeiter": "worker", "frau": "woman", "mann": "man",
    "milizionaer": "militiaman", "milizionär": "militiaman", "miliz": "militia", "nonne": "nun",
    "priester": "priest", "revolverheld": "gunslinger", "revolver": "revolver", "goucho": "gaucho",
    "goutcho": "gaucho", "seniorita": "senorita", "siedler": "settler", "siedlerin": "settler_woman",
    "krankenschwester": "nurse", "trapper": "trapper", "cowboy": "cowboy", "sheriff": "sheriff",
    "pionier": "pioneer", "pioneer": "pioneer", "gatling": "gatling", "kanone": "cannon",
    "kanonkugel": "cannonball", "kugel": "ball", "planwagen": "covered_wagon",
    "postkutsche": "stagecoach", "kutsche": "coach", "kut": "coach", "gepkutsche": "armoured_coach",
    "kutscheverg": "coach_upgrade", "wagen": "wagon", "transportwagen": "transport_wagon",
    "transport": "transport", "transporter": "transporter", "trans": "transport",
    "flussboot": "riverboat", "boot": "boat", "floss": "raft", "flossgmf": "raft", "kanu": "canoe",
    "travois": "travois", "travoi": "travois", "krieger": "warrior", "speerkaempfer": "spearman",
    "speerkämpfer": "spearman", "speer": "spear", "messerwerfer": "knife_thrower",
    "messer": "knife", "tomahawkwerfer": "tomahawk_thrower", "tomahawkwerfen": "tomahawk_throw",
    "tomahawk": "tomahawk", "bogenschuetze": "archer", "bogenschütze": "archer",
    "bogenschützen": "archers", "bogen": "bow", "brandpfeilschuetze": "fire_archer",
    "brandpfeilschütze": "fire_archer", "brandpfeil": "fire_arrow", "brand": "fire_arrow",
    "pfeil": "arrow", "gewehrschuetze": "rifleman", "gewehrschütze": "rifleman",
    "gewehrchütze": "rifleman", "gewehrsch": "rifleman", "gewehr": "rifle", "gun": "gun",
    "pistole": "pistol", "haeuptling": "chief", "häuptling": "chief", "hauptling": "chief",
    "medizinmann": "medicine_man", "medizinann": "medicine_man", "medi": "medicine",
    "medizin": "medicine", "bandenchef": "gang_leader", "chef": "boss", "barbier": "barber",
    "desperado": "desperado", "jaeger": "hunter", "jäger": "hunter", "meuchel": "assassin",
    "meuchelmörder": "assassin", "peitsche": "whip", "peitschenschwinger": "whip_man",
    "sprengmeister": "blaster", "sprengstoffexperte": "explosives_expert", "saboteur": "saboteur",
    "ironclad": "ironclad", "mensch": "human", "menschpferd": "rider", "reiter": "rider",
    # --- heroes (names stay)
    "custer": "custer", "crocket": "crockett", "bowie": "bowie", "travis": "travis",
    "beecher": "beecher", "fetterman": "fetterman", "santa": "santa", "ana": "anna",
    "crazy": "crazy", "horse": "horse", "crow": "crow", "little": "little", "gall": "gall",
    "jessie": "jesse", "billy": "billy", "sam": "sam",
    # --- animals
    "animals": "animals", "tier": "animal", "bueffel": "buffalo", "büffel": "buffalo",
    "kuh": "cow", "pferd": "horse", "pferde": "horses", "pfer": "horse", "adler": "eagle",
    "moewen": "gulls",
    # --- buildings
    "kirche": "church", "kirchemex": "church", "bank": "bank", "hauptquartier": "headquarters",
    "hq": "headquarters", "hqmex": "headquarters", "hqusa": "headquarters",
    "kommandantur": "command_post", "kommandatur": "command_post", "wohnhaus": "house",
    "wohn": "dwelling", "wohnbaracke": "barracks_house", "wohnraum": "living_space",
    "kaserne": "barracks", "kasernemex": "barracks", "cantina": "cantina", "cantinamex": "cantina",
    "kloster": "monastery", "handel": "trade", "handelmex": "trading_post",
    "handelsposten": "trading_post", "handelshaus": "trading_house", "finca": "finca",
    "turm": "tower", "wachturm": "watchtower", "schlachthof": "slaughterhouse",
    "goldmine": "gold_mine", "mine": "mine", "fort": "fort", "ranch": "ranch", "farm": "farm",
    "trapperhaus": "trapper_lodge", "trapperhuette": "trapper_lodge", "lager": "store",
    "lagerhaus": "warehouse", "goldlager": "gold_store", "lagerstaette": "camp",
    "ausbildung": "training", "ausbildungslager": "training_camp", "ausbildungszelt": "training_tent",
    "trainingscamp": "boot_camp", "training": "training", "trainings": "training",
    "saegewerk": "sawmill", "sägewerk": "sawmill", "säge": "saw", "hacienda": "hacienda",
    "fleischerei": "butchery", "metzgerei": "butchery", "metzger": "butcher",
    "waffen": "weapons", "waffenfabrik": "weapons_factory", "fabrik": "factory",
    "magazin": "magazine", "magazinmex": "magazine", "acker": "field", "ackerstück": "field_plot",
    "feld": "field", "feuerstelle": "fireplace", "holzverarbeitung": "woodworks",
    "medizinmannzelt": "medicine_tent", "koppel": "corral", "pferdekoppel": "corral",
    "tierverarbeitung": "hide_works", "totem": "totem", "wohnzelt": "tepee", "zelt": "tent",
    "zelte": "tents", "zeltalt": "elders_tent", "altenzelt": "elders_tent", "altzelt": "elders_tent",
    "alten": "elders", "hauptzelt": "chiefs_tepee", "häuptlingszelt": "chiefs_tepee",
    "raucher": "smoke_signal", "rauchstelle": "smoke_signal", "räucherstelle": "smoke_signal",
    "raeucher": "smoke_signal", "tarnzelt": "camouflage_tent", "zeltderahnen": "ancestors_tent",
    "ahnen": "ancestors", "der": "of_the", "fallgrube": "pitfall", "falle": "trap",
    "fallen": "trap", "bootswerft": "shipyard", "werft": "shipyard", "bootshaus": "boathouse",
    "barrikade": "barricade", "ecke": "corner", "links": "left", "rechts": "right",
    "basis": "base", "drugstore": "drugstore", "drug": "drug", "hotel": "hotel",
    "jagdhuette": "hunting_lodge", "jagd": "hunt", "keller": "cellar", "restaurant": "restaurant",
    "saloon": "saloon", "schnaps": "schnapps", "schnapps": "schnapps",
    "schnappsbrennerei": "distillery", "schnapsbrenerei": "distillery",
    "spaehposten": "lookout", "spähposten": "lookout", "ausguck": "lookout",
    "sprengstoff": "explosives", "sprenghuete": "explosives_hut", "sprengstoffhütte": "explosives_hut",
    "tischlerei": "carpentry", "tisch": "table", "mauer": "wall", "palisade": "palisade",
    "kutschenfertigung": "coach_works", "kutschen": "coaches", "sheriff-office": "sheriff_office",
    "office": "office", "bruecke": "bridge", "brücke": "bridge", "anfang": "start", "mitte": "middle",
    "ende": "end", "alamo": "alamo", "sonder": "special", "kornspeicher": "granary",
    "store": "store",
    # --- nature
    "baeume": "trees", "baum": "tree", "laub": "deciduous", "nadel": "conifer", "busch": "bush",
    "buesche": "bushes", "kakteen": "cacti", "kaktus": "cactus", "kak": "cactus", "steine": "rocks",
    "stein": "rock", "sonderstein": "rock_pile", "steinhaufen": "rock_pile", "aufgang": "ramp",
    "gross": "large", "groß": "large", "gorss": "large", "gr": "large", "mittel": "medium",
    "klein": "small", "kl": "small", "go": "large", "ohne": "without", "heu": "hay",
    "landschaft": "landscape", "steppe": "prairie", "wiese": "meadow", "kleinsteppe": "small_prairie",
    "kleinwiese": "small_meadow", "minimap": "minimap", "wasser": "water",
    # --- actions (animation sheets)
    "laufen": "walk", "laufe": "walk", "stehen": "idle", "steht": "idle", "sterben": "die",
    "sterebn": "die", "schiessen": "shoot", "kaempfen": "fight", "kämpfen": "fight",
    "kampf": "fight", "fern": "ranged", "stechen": "stab", "zustechen": "stab", "werfen": "throw",
    "hacken": "chop", "haemmern": "hammer", "bauen": "build", "tragen": "carry",
    "schleppen": "drag", "ernten": "harvest", "abernten": "harvest", "abgeerntet": "harvested",
    "erlegen": "butcher", "ausbeinen": "debone", "heilen": "heal", "tanzen": "dance",
    "singen": "sing", "tarnen": "hide", "tarn": "camouflage", "entarnen": "unhide",
    "einbuddeln": "dig_in", "buddel": "dig", "swim": "swim", "schwimmen": "swim",
    "schwim": "swim", "schwimmt": "swims", "paddeln": "paddle", "fahren": "drive", "reiten": "ride",
    "reitenstehen": "ride_idle", "pferdstehen": "horse_idle", "fliehen": "flee",
    "langweilen": "bored", "saehen": "sow", "sähen": "sow", "sähene": "sow", "pause": "pause",
    "angriff": "attack", "angegriffen": "attacked", "bekehren": "convert", "verrotten": "decay",
    "zusammenfallende": "collapsing", "zusammenfallendes": "collapsing", "brennendes": "burning",
    "ausgeraubt": "robbed", "fertig": "finished", "gebaut": "built", "einschlag": "impact",
    "wiehern": "neigh", "schnauben": "snort", "pferdegetrabe": "horse_trot", "muh": "moo",
    "gemuhe": "mooing", "blub": "bubble", "blubb": "bubble", "wasserplatschen": "water_splash",
    "anklicken": "select", "ausführen": "acknowledge", "bewegen": "move", "befehl": "order",
    "erreicht": "reached", "kein": "no", "keine": "no", "nicht": "not", "bebaubar": "buildable",
    "bevölkerungslimit": "population_limit", "mehr": "more", "ressourcen": "resources",
    "resourcenicons": "resource_icons", "dest": "destroyed", "destroy": "destroyed",
    "zauber": "spell", "kampfgeist": "fighting_spirit", "aura": "aura",
    "sammeln": "gather", "korb": "basket", "sack": "sack", "holz": "wood", "gold": "gold",
    "rest": "rest", "auf": "up", "aus": "out", "ins": "into", "mit": "with", "vom": "from",
    "wird": "is", "shad": "shadow", "shadow": "shadow", "sahdow": "shadow", "schatten": "shadow",
    "stehenschatten": "idle_shadow", "zschatten": "shadow", "kurz": "short", "lang": "long",
    "short": "short", "single": "single", "static": "static", "red": "red",
    # --- effects
    "explosion": "explosion", "explosiv": "explosion", "feuer": "fire", "fire": "fire",
    "rauch": "smoke", "rauchwolke": "smoke_cloud", "wolke": "cloud", "cloud": "cloud",
    "blitzwolke": "lightning_cloud", "blitz": "lightning", "donner": "thunder",
    "hagelwolke": "hail_cloud", "hagel": "hail", "regenwolke": "rain_cloud", "regen": "rain",
    "schutzschirm": "shield", "sensor": "sensor", "sensorx": "sensor_x", "fog": "fog",
    "comsat": "comsat", "positionsfahne": "rally_flag", "zeiger": "pointer", "wind": "wind",
    "dynamit": "dynamite", "dynamitschnur": "dynamite_fuse",
    # --- interface
    "menues": "menus", "menu": "menu", "main": "main", "mainmenu": "main_menu",
    "selectgame": "select_game", "selectkampagne": "select_campaign",
    "selectmission": "select_mission", "selectnetname": "select_net_name",
    "selectplayer": "select_player", "selectm": "select_m", "abrechnung": "statistics",
    "accept": "accept", "chat": "chat", "credits": "credits", "creditsblack": "credits_black",
    "einstellungen": "settings", "ingameeinstellungen": "ingame_settings",
    "ingamemulti": "ingame_multiplayer", "kampagne": "campaign", "kampagnen": "campaigns",
    "karteladen": "load_map", "karte": "map", "loadmenu": "load_menu", "laden": "load",
    "mission": "mission", "missionen": "missions", "missions": "missions", "multi": "multiplayer",
    "multimenu": "multiplayer_menu", "multiplayertreffpunkt": "multiplayer_lobby", "net": "network",
    "netmenu": "network_menu", "optionen": "options", "optionmenu": "option_menu",
    "savemenu": "save_menu", "singlemenu": "single_menu", "verbindung": "connection",
    "missionmenu": "mission_menu", "ladebild": "loading_screen", "ladebalken": "loading_bar",
    "startbild": "start_screen", "status": "status", "leiste": "bar", "leistelinks": "bar_left",
    "leisterechts": "bar_right", "balken": "bar", "bilderliste": "sheet", "piclist": "sheet",
    "sonstigeicons": "misc_icons", "kleineicons": "small_icons",
    "iconserstereihe": "icons_first_row", "usaeinheiten": "american_units",
    "mexeinheiten": "mexican_units", "indeinheiten": "native_units", "inideinheiten": "native_units",
    "deseinheiten": "outlaw_units", "despeinheiten": "outlaw_units", "usaicons": "american_icons",
    "mexicons": "mexican_icons", "indiicons": "native_icons", "despicons": "outlaw_icons",
    "einheiten_icons": "unit_icons", "potraits": "portraits", "logos": "logos", "about": "about",
    "upgrade": "upgrade", "wegweiser": "signpost", "meldung": "message", "nachricht": "message",
    "anzeigen": "show", "sichtradius": "sight_radius", "uhr": "clock", "tür": "door",
    "add": "add", "click": "click", "ding": "ding", "notify": "notify", "silence": "silence",
    "tut": "toot", "action": "action", "properties": "properties", "performance": "performance",
    "wires": "wires", "china": "china", "on": "on", "tisch": "table", "umfärben": "recolour",
    "font": "font", "fonts": "fonts", "black": "black", "text": "text", "texte": "texts",
    # --- sound
    "sfx": "sounds", "sound": "", "voices": "voices", "gewonnen": "won", "verloren": "lost",
    "missions2": "missions", "static2": "static", "pistolenschuss": "pistol_shot",
    "gewehrschuss": "rifle_shot", "schuss": "shot", "zz": "zz", "zzz": "zzz", "zzzz": "zzzz",
    # --- data
    "guids": "guids", "guids2": "guids", "defs": "defs", "defaults": "defaults", "ids": "ids",
    "rules": "rules", "bobliste": "object_types", "sfxguids": "sound_table", "leveled": "level_editor",
    "leveleditor": "level_editor", "editor": "editor", "daten": "data", "startpunkt": "start_point",
    "guidliste": "guid_list", "kampagne2": "campaign",
    # --- abbreviations in object type names
    "st": "prairie", "wi": "meadow", "stone": "plateau", "ul": "bottom_left", "ur": "bottom_right",
    "ol": "top_left", "or": "top_right", "ahnenzelt": "ancestors_tent", "befehlshpferd": "commander_horse",
    "bogensch": "archer", "brandpfeilsch": "fire_archer", "fetter": "fetterman", "fettermann": "fetterman",
    "fluß": "river", "haus": "house", "kavall": "cavalryman", "kschwester": "nurse",
    "kutschenfert": "coach_works", "pal": "palisade", "peitschenschw": "whip_man", "plan": "covered",
    "pritschenwagen": "flatbed_wagon", "sheriffoff": "sheriff_office", "spreng": "blast",
    "sprenghuette": "explosives_hut", "tierverarb": "hide_works", "abr": "statistics",
    "tit": "title", "briefing": "briefing", "bar": "barricade", "son": "special",
}
# Names of people (heroes) and other words that are fine as they are.
NAMES = ["collins", "david", "houston", "james", "jim", "kid", "nose", "roman", "weirs", "mounted",
         "l", "r", "s", "w"]

# Folder renames applied to the leading part of a path (longest prefix first). The rest of
# the path is translated word by word.
FOLDERS = [
    ("global/gfx/usa/sonstigeicons", "interface/icons/misc"),
    ("global/gfx/usa/icons/einheiten", "interface/icons/units/americans"),
    ("global/gfx/mex/icons/einheiten", "interface/icons/units/mexicans"),
    ("global/gfx/ind/icons/einheiten", "interface/icons/units/natives"),
    ("global/gfx/des/icons/einheiten", "interface/icons/units/outlaws"),
    ("global/gfx/usa/icons", "interface/icons/americans"),
    ("global/gfx/mex/icons", "interface/icons/mexicans"),
    ("global/gfx/ind/icons", "interface/icons/natives"),
    ("global/gfx/des/icons", "interface/icons/outlaws"),
    ("global/gfx/usa/zeiger", "interface/pointer"),
    ("global/gfx/positionsfahne", "interface/rally_flag"),
    ("global/gfx/status/leiste", "interface/hud/bar"),
    ("global/gfx/status/resourcenicons", "interface/hud/resource_icons"),
    ("global/gfx/status", "interface/hud"),
    ("global/gfx/menues", "interface/menus"),
    ("global/gfx/ladebild", "interface/loading_screen"),
    ("global/gfx/usa", "units/americans"),
    ("global/gfx/mex", "units/mexicans"),
    ("global/gfx/ind", "units/natives"),
    ("global/gfx/des", "units/outlaws"),
    ("global/gfx/animals", "animals"),
    ("global/gfx/verrotten", "effects/decay"),
    ("global/gfx", "effects"),
    ("steppe/gfx/usa", "buildings/americans"),
    ("steppe/gfx/mex", "buildings/mexicans"),
    ("steppe/gfx/ind", "buildings/natives"),
    ("steppe/gfx/des", "buildings/outlaws"),
    ("steppe/gfx/sonder", "buildings/special"),
    ("steppe/gfx/elemente", "nature/prairie"),
    ("wiese/gfx/elemente", "nature/meadow"),
    ("steppe/gfx/landschaft", "terrain/prairie"),
    ("wiese/gfx/landschaft", "terrain/meadow"),
    ("potraits/einheiten_icons/usa", "portraits/units/americans"),
    ("potraits/einheiten_icons/mex", "portraits/units/mexicans"),
    ("potraits/einheiten_icons/indi", "portraits/units/natives"),
    ("potraits/einheiten_icons/desp", "portraits/units/outlaws"),
    ("potraits/einheiten_icons", "portraits/units"),
    ("potraits/gebäude_icons/usa", "portraits/buildings/americans"),
    ("potraits/gebäude_icons/mex", "portraits/buildings/mexicans"),
    ("potraits/gebäude_icons/indi", "portraits/buildings/natives"),
    ("potraits/gebäude_icons/desp", "portraits/buildings/outlaws"),
    ("potraits/sonstige_icons", "portraits/other"),
    ("sfx/static2", "sounds/effects"),
    ("sfx/static", "sounds/effects"),
    ("sfx/missions2", "sounds/missions"),
    ("sfx/missions", "sounds/missions"),
    ("sfx/voices/medizinmann tanzen", "sounds/voices/medicine_man_dance"),
    ("sfx/voices/sterben frau", "sounds/voices/dying_woman"),
    ("sfx/voices/sterben mann", "sounds/voices/dying_man"),
    ("sfx/voices", "sounds/voices"),
    ("sfx", "sounds"),
]

# Animation-sheet word combinations whose word-by-word translation would read badly.
PHRASES = {
    "holz hacken": "chop_wood", "holz_hacken": "chop_wood", "nicht bebaubar": "not_buildable",
    "stehen_reiten": "ride_idle", "ohne_pferd": "without_horse", "kaempfen_fern": "fight_ranged",
    "medizinmann tanzen": "medicine_man_dance",
    "_des": "_destroyed",  # wagons' wreck sheets (05_des.spx); "des" alone is the outlaws
}
